### ISSUE TITLE
Add Swagger annotations in 'RETRIEVE A PROMOTION BY ID' (READ)

### ISSUE THREAD

**Issue by tcm390** [nyu-devops-2021-summer-promotions/promotions#119]
**As a** user 
**I need** a READ Swagger Docs
**So that**  we can use the API

**Assumptions:** 
* We would use Swagger
* update **get_promotions** under the **PromotionResource** #118 class in the **routes.py**
* add **marshal_with**
* add 404 descriptions in the **response**

**Acceptance Criteria:**
```
Given the /apidocs/
When we try to access GET /promotions/{id} in the doc
Then we can see Parameters(id) and Responses code(404), and Responses 200 with response json values

When we send READ request(Try it out) with existing ID by following the doc
Then I can get code 200 and the response as the doc said

When we send READ request(Try it out) with NOT existing ID by following the doc
Then I can get code 404 

Given get_promotion function in PromotionResource Class
Then swagger annotations exist
```

**Comment by Pmahindra93** [comment]
Passed all Travis CI checks
- Tested the API and 200 response was returned (server response)
