### ISSUE TITLE
Add Swagger annotations in 'CREATE' 

### ISSUE THREAD

**Issue by shihokuni** [nyu-devops-2021-summer-promotions/promotions#121]
**As a** user 
**I need** a CREATE Swagger Docs
**So that**  we can use the API

**Assumptions:** 
* We would use Swagger
* update **create_promotions** under the **PromotionCollection** #126  in the **routes.py**
* add **expect** with **create_model**
* add **marshal_with** with **code=201**
* add 400 descriptions in the **response**

**Acceptance Criteria:**
```
Given the /apidocs/
When we try to access POST /promotions in the doc
Then we can see Parameters(create_model) and Responses code(400), and Responses 201 with response json values

When we send CREATE request(Try it out) with all requirement parameters by following the doc
Then I can get code 201 and the response as the doc said
And I can see the promotion (e.g., by using LIST)

When we send CREATE request(Try it out) with NOT all requirement parameters by following the doc
(e.g., request body does not have "start_date")
Then I can get code 400 
And I don't see the promotion (e.g., by using LIST)

Given create_promotions function in PromotionCollection Class
Then swagger annotations exist
```

**Comment by abdulrahimq** [comment]
Tried 
- 201 | Success Example 
- 400 | The posted data was not valid
- 415 | Invalid Content Type
They all work! 

</span></span>
