### ISSUE TITLE
Add Swagger annotations in 'Activate'

### ISSUE THREAD

**Issue by tcm390** [nyu-devops-2021-summer-promotions/promotions#123]
**As a** user  
**I need** a Activate Swagger Docs 
**So that** we can use the API  

**Assumptions:** 
* We would use Swagger
* update `activate_promotions` under the `ActivateResource` class #128 in the `routes.py`
* add 404 descriptions in the `response`
* add `marshal_with`

**Acceptance Criteria:**

```
Given the /apidocs/
When we try to activate promotion in the doc
Then we can see Responses code(404,200) with response json values

When we send activate request(Try it out) with existing id
Then I can get code 200 and the response as the doc said
And the promotion is activated 

When we send activate request(Try it out) with non-existing id
Then I would get code 404 and the response as the doc said

Given activate_promotions function in ActivateResource Class
Then swagger annotations exist
```

**Comment by shihokuni** [comment]
We can see all response codes we need, and it worked from /apidocs `Try it out` !

**Comment by shihokuni** [comment]
We can see all response codes we need, and it worked from /apidocs `Try it out` !
