### ISSUE TITLE
Add Swagger annotations in 'Deactivate'

### ISSUE THREAD

**Issue by tcm390** [nyu-devops-2021-summer-promotions/promotions#124]
**As a** user  
**I need** a Deactivate Swagger Docs 
**So that** we can use the API  

**Assumptions:** 
* We would use Swagger
* update `deactivate_promotions` under the` DeactivateResource` class #128 in the `routes.py`
* add 404 descriptions in the `response`
* add `marshal_with`

**Acceptance Criteria:**

```
Given the /apidocs/
When we try to deactivate promotion in the doc
Then we can see Responses code(404,200) with response json values

When we send deactivate request(Try it out) with existing id
Then I can get code 200 and the response as the doc said
And the promotion is deactivated 

When we send deactivate request(Try it out) with non-existing id
Then I would get code 404 and the response as the doc said

Given deactivate_promotions function in DeactivateResource Class
Then swagger annotations exist
```

**Comment by shihokuni** [comment]
We can see all response codes we need, and it worked from /apidocs `Try it out` !

**Comment by shihokuni** [comment]
We can see all response codes we need, and it worked from /apidocs `Try it out` !
