### ISSUE TITLE
Create PromotionCollection Class for refactoring

### ISSUE THREAD

**Issue by tcm390** [nyu-devops-2021-summer-promotions/promotions#126]
**As a** developer
**I need** to refactor current routes.py
**So that** it uses flask-restx

**Assumptions:** 
* we are going to be making CRUD action changes later
* we are just creating this particular class and moving the related actions into it
* related actions are `list_promotions` , `create_promotions`
* PATH: /promotions

**Acceptance Criteria:**
```
Given routes.py
When locating crud actions relating to querying 
Then the actions are all class methods of PromotionCollection Class

Given PromotionCollection Class
When checking api routes
Then route per class instead of route per method

```

**Comment by shihokuni** [comment]
This is merged by #135 and finished review
