### ISSUE TITLE
Add Swagger annotations in 'DELETE'

### ISSUE THREAD

**Issue by shihokuni** [nyu-devops-2021-summer-promotions/promotions#127]
**As a** user 
**I need** a DELETE Swagger Docs
**So that** we can use the API

**Assumptions:** 
* We would use Swagger
* update **delete_promotions** under the **PromotionResouce** #118 in the **routes.py**
* add 204 descriptions in the **response**

**Acceptance Criteria:**
```
Given the /apidocs/
When we try to access DELETE /promotions/{promotion_id} in the doc
Then we can see Parameters(id) and Responses code(204)

When we send DELETE request(Try it out) with existing ID
Then I can get code 204
And I do not see the promotion anymore (e.g., by using LIST)

When we send DELETE request(Try it out) with not existing ID
Then I can get code 204

Given delete_promotions function in PromotionResource Class
Then swagger annotations exist
```

**Comment by shihokuni** [comment]
@jtsen Can you check below, and feel free to update
Add response code *400* did not exist in the lab code, but when I set not existing ID, the code was 400. I think it is not unusual case, so that I added it in the doc.

**Comment by shihokuni** [comment]
> @jtsen Can you check below, and feel free to update
> Add response code _400_ did not exist in the lab code, but when I set not existing ID, the code was 400. I think it is not unusual case, so that I added it in the doc.

Actually, when we set not exist id, should get 204 not 400. I updated the acceptance criteria

**Comment by tcm390** [comment]
Just checked the code and this seems to be already done. And I also test in UI. When I input any number in ID field(even non-exist ID), it would always return 204.

**Comment by shihokuni** [comment]
The test result seems fine!
