### ISSUE TITLE
Change `dev` hotname

### ISSUE THREAD

**Issue by shihokuni** [nyu-devops-2021-summer-promotions/promotions#133]
**As a** developer
**I need** to change `dev` host name
**So that** we can create separate environment against `prod`

**Assumptions:** 
* add `-dev` for the hostname at the `dev` space

**Acceptance Criteria:**
```
Given IBM cloud
When the developer push commit
Then `Build`, `Deploy` and `Test` pipeline are still working
```

**Comment by jtsen** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/12847f01-db08-4f28-a98c-cc3e34de22cc?env_id=ibm:yp:us-south "nyu-promotion-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/fb67b460-e0db-4e33-aea8-c6c52f1e08e6 "nyu-promotion-service-sum21") deployed [promotions](https://github.com/nyu-devops-2021-summer-promotions/promotions/releases/tag/deploy-ibm-yp-us-south-promotions-prod-20210807-162945 "deploy-ibm-yp-us-south-promotions-prod-20210807-162945") to [prod](https://console.bluemix.net/apps/b60cc3cc-1522-45d8-84c0-fde436d5ba0a?env_id=ibm:yp:us-south "ibm:yp:us-south:promotions:prod"), including commit c7fcc1fbc3cba13ba0ff89d30f0149dfa78f6c13

**Comment by jtsen** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/12847f01-db08-4f28-a98c-cc3e34de22cc?env_id=ibm:yp:us-south "nyu-promotion-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/16f331a4-d230-45e7-9c37-485e9493ffca "ui-test") deployed [promotions](https://github.com/nyu-devops-2021-summer-promotions/promotions/releases/tag/deploy-ibm-yp-us-south-promotions-dev-20210810-224327 "deploy-ibm-yp-us-south-promotions-dev-20210810-224327") to [dev](https://console.bluemix.net/apps/75ded29c-befd-4fc9-9ead-2f110b9d7bf7?env_id=ibm:yp:us-south "ibm:yp:us-south:promotions:dev"), including commit c7fcc1fbc3cba13ba0ff89d30f0149dfa78f6c13
