### ISSUE TITLE
Update Promotion

### ISSUE THREAD

**Issue by abdulrahimq** [nyu-devops-2021-summer-promotions/promotions#15]
**As a** store manager with promotion
**I need** to update the promotion 
**So that** the promotion should reflect updates to users

**Assumptions:** 
* Update /promotions/{id} 
* add `app.route("/promotions/<int:promotion_id>", methods=["PUT"]) ` and def `update_promotions(promotion_id)` in the `"route.py"`
* add def `save` in the `"model.py"`
* Call other microservice APIs to update the promotion information.

**Acceptance Criteria:**
```
Given an UPDATE (PUT) request to update the promotion information
When the user responsible for the information of a promotion wants to change the information of the promotion
Then the new updates are reflected for all the other users and microservices that might show the promotion. 
```

**Comment by jtsen** [comment]
I think this goes hand-in-hand with stories #10 and #9. With regards to implementing the same checks on existing records and their current values. 

Maybe we should aggregate these?
