### ISSUE TITLE
List Promotions

### ISSUE THREAD

**Issue by tcm390** [nyu-devops-2021-summer-promotions/promotions#3]
**As a** store manager
**I need** to see all promotions
**So that** I can check the status of all promotions

**Assumptions:** 
* The list would show all promotions and the status of the promotions
* add `app.route("/promotions", methods=["GET"]) ` and def `list_promotions` in the `"route.py"`
* add def `all` in the `"model.py"`

**Acceptance Criteria:**
 
```
Given a Get request
When I query the table
Then it would return the information I needed
```

**Comment by abdulrahimq** [comment]
Just minor thing but probably would be better to name it list promotions

**Comment by abdulrahimq** [comment]
And I think it will be better to add more text to the assumptions.
