### ISSUE TITLE
Create .travis.yml for TDD testcases

### ISSUE THREAD

**Issue by shihokuni** [nyu-devops-2021-summer-promotions/promotions#46]
**As a** developer
**I need** to run autotest for TDD
**So that** we can realize ready for pull/push

**Assumptions:** 
* create a .travis.yml file
* configure Travis CI to run TDD test cases

**Acceptance Criteria:**
```
Given repo
When we push or pull
Then the TDD test runs and gets results
```

**Comment by jtsen** [comment]
This is for the step "Add continuous integration to every pull request" right? Just making sure here as I review the stories and try to add more.

**Comment by shihokuni** [comment]
Yes!! Exactly, and I added all stories of **Requirement 1: Add Continuous Integration** ( I separated TDD and BDD for some stories like #46 ). So that, if you think I miss some stories of Requirement 1, please add it!

**Comment by jtsen** [comment]
We might want to take the professor's travis.yml file contents and put it in ours.

**Comment by jtsen** [comment]
we could maybe change the name of the db from "travis_ci_test" to something like "testdb" ? It probably wouldn't make much of a difference but just an idea.

**Comment by shihokuni** [comment]
> we could maybe change the name of the db from "travis_ci_test" to something like "testdb" ? It probably wouldn't make much of a difference but just an idea.

Thank you!!! I agree with your idea!
I committed as #85
