### ISSUE TITLE
Update .travis.yml for BDD testcases

### ISSUE THREAD

**Issue by shihokuni** [nyu-devops-2021-summer-promotions/promotions#47]
**As a** developer
**I need** to run autotest for BDD
**So that** we can realize ready for pull/push

**Assumptions:** 
* create a .travis.yml file
* configure Travis CI to run BDD test cases

**Acceptance Criteria:**
```
Given repo
When we push or pull
Then the BDD test runs and gets results
```

**Comment by jtsen** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/12847f01-db08-4f28-a98c-cc3e34de22cc?env_id=ibm:yp:us-south "nyu-promotion-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/fb67b460-e0db-4e33-aea8-c6c52f1e08e6 "nyu-promotion-service-sum21") deployed [promotions](https://github.com/nyu-devops-2021-summer-promotions/promotions/releases/tag/deploy-ibm-yp-us-south-promotions-dev-20210729-191732 "deploy-ibm-yp-us-south-promotions-dev-20210729-191732") to [dev](https://console.bluemix.net/apps/ca1a3732-4e6f-44cb-a4a8-07d1caad0cab?env_id=ibm:yp:us-south "ibm:yp:us-south:promotions:dev"), including commits e11ac06aa0fc8578f76d665a6ef2faa3ddbcd827, 5a92fe9b0a2081f3c10523b4344b9180b744cbad, 4410351ce94aaa87f2f08f0c1be1a69b81479ee9

**Comment by jtsen** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/12847f01-db08-4f28-a98c-cc3e34de22cc?env_id=ibm:yp:us-south "nyu-promotion-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/fb67b460-e0db-4e33-aea8-c6c52f1e08e6 "nyu-promotion-service-sum21") deployed [promotions](https://github.com/nyu-devops-2021-summer-promotions/promotions/releases/tag/deploy-ibm-yp-us-south-promotions-prod-20210807-162945 "deploy-ibm-yp-us-south-promotions-prod-20210807-162945") to [prod](https://console.bluemix.net/apps/b60cc3cc-1522-45d8-84c0-fde436d5ba0a?env_id=ibm:yp:us-south "ibm:yp:us-south:promotions:prod"), including commits e11ac06aa0fc8578f76d665a6ef2faa3ddbcd827, 5a92fe9b0a2081f3c10523b4344b9180b744cbad, 4410351ce94aaa87f2f08f0c1be1a69b81479ee9
