### ISSUE TITLE
Add test coverage results of TDD

### ISSUE THREAD

**Issue by shihokuni** [nyu-devops-2021-summer-promotions/promotions#49]
**As a** developer
**I need** to know the autotest coverage of TDD
**So that** we can pull or merge only when the cover is more than 95%

**Assumptions:** 
* using Codecov
* maintaining 95%+ code coverage for TDD
* add badge in README

**Acceptance Criteria:**
```
Given repo
When TDD autotest runs
Then the test coverage is shown (more than 95%) as a badge too
```

**Comment by shihokuni** [comment]
Is the **Acceptance Criteria:** enough only we can see the test coverage?

**Comment by abdulrahimq** [comment]
We are talking about Codecover badge.
