### ISSUE TITLE
Add Cloud Foundry metadata files 

### ISSUE THREAD

**Issue by jtsen** [nyu-devops-2021-summer-promotions/promotions#54]
**As a** developer
**I need** Cloud Foundry metadata files
**So that** IBM Cloud will know how to deploy our application

**Assumptions:** 
* Team set up on cloud foundry
* Flask app created in IBM South server
* Updated Vagrantfile with IBM Cloud CLI installed

**Acceptance Criteria:**
```
Given  a Python Flask app
When deploying to the cloud
Then IBM cloud can auto-detect metadata files
```
```
Given our directory
When checking out the root repository
Then requriements.txt, manifest.yml, Procfile exists and is setup.
```

**Comment by shihokuni** [comment]
@jtsen 
Hi! Is this ticket scope including **Create a Python Flask Cloud Foundry application in IBM Cloud - US South.** ?
I thought it is included and we can see **nyu-devops-promotions.us-south.cf.appdomain.cloud** in the IBM cloud.
