### ISSUE TITLE
Design file structure 

### ISSUE THREAD

**Issue by shihokuni** [nyu-devops-2021-summer-promotions/promotions#6]
**As a** Developer
**I need** to decide file structure
**So that** developers can start developing

**Assumptions:** 
* decide file structure
* decide file name (e.g., model.py, status.py, etc)
* write file description 

**Acceptance Criteria:**
```
Given folder and files
When developers read each file
Then understand each file role and start writing code in the appropriate file
```

**Comment by jtsen** [comment]
Just a comment to take note of meeting discussion:

In this story, we should have setup empty files (such as models.py) so we could start branching with these files and developing.
