### ISSUE TITLE
Flask-RESTX refactor (Ensure HTTP errors return JSON error messages)

### ISSUE THREAD

**Issue by Pmahindra93** [nyu-devops-2021-summer-promotions/promotions#65]
**As** a developer
**I need** to ensure the refactored Flask-RESTX code with HTTP errors return json error messages and not HTML errors
**So that** error messages can be conveyed to the client

**Acceptance Criteria:**
```
When HTTP errors are initiated
Then the app returns json error messages and not HTML errors
```

**Comment by shihokuni** [comment]
Could you update `Acceptance Criteria` to gherkin format if you know what we need to check after the lecture?
