### ISSUE TITLE
Connect this DevOps pipeline to the GitHub repository

### ISSUE THREAD

**Issue by abdulrahimq** [nyu-devops-2021-summer-promotions/promotions#67]
**As a** Developer
**I need** to connect my pipeline to the GitHub repo 
**So that** when I merge branches then it will go to the repo and test immediately. 

**Assumptions:** 
* ...

**Acceptance Criteria:**
```
Given ...
When ...
Then ...
```

**Comment by jtsen** [comment]
This has to have been done with the two stage delivery pipeline owo.
