### ISSUE TITLE
Unit Test Job

### ISSUE THREAD

**Issue by abdulrahimq** [nyu-devops-2021-summer-promotions/promotions#68]
**As a** Developer
**I need** to run the unit test in the build stage
**So that** when I build the code I know that new changes didn't break anything 

**Assumptions:** 
* We have access to a pipeline

**Acceptance Criteria:**
```
Given ...
When ...
Then ...
```

**Comment by jtsen** [comment]
I also think this has been done in the two stage delivery pipeline. Please correct me if I'm wrong.
