### ISSUE TITLE
create and test Test stage

### ISSUE THREAD

**Issue by abdulrahimq** [nyu-devops-2021-summer-promotions/promotions#69]
**As a** Developer  
**I need** a Test stage in the pipeline
**So that** I can run BDD test before deploy to Production

**Assumptions:** 
* run your integration tests with **behave** against the Dev deployment

**Acceptance Criteria:**
```
Given a commit to the master branch
When previous stages (Build, Deploy) passed
Then successfully run bdd test
When previous stages (Build, Deploy) failed
Then Test stage does not run
```

**Comment by jtsen** [comment]
I think this has been done with the two stage delivery pipeline. Please correct me if I'm wrong.

**Comment by shihokuni** [comment]
As you already know, we have `Build` and `Deploy`, but not yet `Test` :D 
We need to keep open the thicket!

**Comment by shihokuni** [comment]
> I think this has been done with the two stage delivery pipeline. Please correct me if I'm wrong.

As you already know, we have `Build` and `Deploy`, but not yet `Test` :D 
We need to keep open the ticket!
