### ISSUE TITLE
Push application to IBM Cloud

### ISSUE THREAD

**Issue by jtsen** [nyu-devops-2021-summer-promotions/promotions#72]
**As a** developer
**I need** to push the application to IBM cloud
**So that** the service runs on the cloud

**Assumptions:** 
* use **ibmcloud cf push** command
* also still working in the vagrant VM with the command: honcho start

**Acceptance Criteria:**
```
Given IBM Cloud
When we access the URL of your service
Then the service is working

Given vagrantVM
When we run honcho start
Then the service is working in the localhost
```

**Comment by shihokuni** [comment]
![スクリーンショット 2021-07-20 18 37 29](https://user-images.githubusercontent.com/44769660/126404526-0b1b2fcf-b3b8-4948-a9a8-8a403a9701eb.png)
I think this information is helpful.
We will use  **ElephantSQL   user-provided            nyu-promotion-service-sum21**  
(not **Cloudant      cloudantNoSQLDB** )

Also here is the command to create ElephantSQL in IBM cloud.(some parts are masked)
`ic cf cups ElephantSQL -p '{"url":"postgres://xvtXXXm:BeMqYhXXXXXXXQ7qLF@baXXr.db.elephantsql.com:5432/xvtXXXXm"}'`

**Comment by Pmahindra93** [comment]
Shisho and Jeff, I'm confused here
First of all - we need to edit the config.py file right? And not the models.py?
Also, Shiho - thanks for the information provided but don't I just need to add the three lines provided by Professor on Slack?
