### ISSUE TITLE
Setup ElephantSQL server

### ISSUE THREAD

**Issue by jtsen** [nyu-devops-2021-summer-promotions/promotions#73]
**As a** developer
**I need** a postgres db running on elephantSQL cloud
**So that** I can pass in the URI as an environment variable 

**Assumptions:** 
* we are still using postgres

**Acceptance Criteria:**
```
Given a manual deployment to the cloud
When providing the URI
Then database successfully added 
```

**Comment by shihokuni** [comment]
Here is a command 
`ibmcloud login -a https://cloud.ibm.com --apikey @~/.bluemix/apiKey.json -r us-south`
`ibmcloud target -o promotions -s dev`

create ElephantSQL in IBM cloud.(some parts are masked)
`ic cf cups ElephantSQL -p '{"url":"postgres://xvtXXXm:BeMqYhXXXXXXXQ7qLF@baXXr.db.elephantsql.com:5432/xvtXXXXm"}'`

The result is below.
![スクリーンショット 2021-07-20 18 00 13](https://user-images.githubusercontent.com/44769660/126401046-cc1a41b3-b6fd-47c1-8a68-bd2ef4bca0a2.png)
