### ISSUE TITLE
modify config.py for cloud deployment and Database connection 

### ISSUE THREAD

**Issue by jtsen** [nyu-devops-2021-summer-promotions/promotions#87]
**As a** Developer
**I need** a config.py file
**So that** we could use Postgres(ElephantSQL) on cloud foundry

**Assumptions:** 
* we are using postgres
* we are using ElephantSQL.com
* we are using cloud foundry

**Acceptance Criteria:**
```
Given config.py file
When pushing to ibm cf
Then able to process VCAP_SERVICES for Postgres and the database functions properly
```

**Comment by Pmahindra93** [comment]
I've done this already Shiho

**Comment by jtsen** [comment]
> I've done this already Shiho

If this is completed, lets link the pull request and close this 🔥

**Comment by shihokuni** [comment]
I changed the link and updated assumptions etc...
