### ISSUE TITLE
activate action for the promotion

### ISSUE THREAD

**Issue by shihokuni** [nyu-devops-2021-summer-promotions/promotions#9]
**As a** promotion team of each product or store
**I need** to activate the promotion
**So that** the promotion is applied for users 

**Assumptions:** 
~~Decide interface to other microservices (e.g., we should call other microservice or other microservice should call `GET /promotions`)~~
~~Decide what other task needs (e.g., send e-mail to customer)~~
~~* Call other microservice APIs to apply for the promotion~~
-> _do not have to interact with other microservices for the homework_
* Create `PUT /promotions/{id}/activate`  that changes the status and pretends to start all other processes such as discount to apply for the promotion. However, in the homework, we will implement only changing the status and recording in the log.

**Acceptance Criteria:**
```
Given a PUT /promotions/{id}/activate  request to activate the promotion
When who has a role in starting promotion want to activate the promotion
Then the status of the promotion is changed to activate
```

**Comment by jtsen** [comment]
I think this goes hand-in-hand with deactivating promotions in the sense that we will probably just store a boolean variable for each promotion indicating whether or not it is active. 

Both will use PUT or PATCH to update this particular column to either TRUE or FALSE (applicable and active / non-applicable and non-active).  Both of these actions will simply need to have a working implementation of updating the database.

Maybe we can aggregate these two tasks?

**Comment by shihokuni** [comment]
@jtsen 
Thank you!  we can implement using "PATCH" as the same as "UPDATE the resource", but I think activate and deactivate is the action as the state change like in the lecture slide. So that, it is the different story of the "Update".
(04-Building-RESTful-Services.pdf P.46~)

**Comment by jtsen** [comment]
@shihokuni 

Thanks for your response. I've looked through the slides. I think our understanding may be a little different. 

What I thought was that the state changes here is not ambiguous. Therefore, we can use PUT in the manner that is shown in slide 46 as we would be able to have something in our model that has a representation of its state. 

Maybe we could revisit this and see what the other team members think. Cheers!

**Comment by shihokuni** [comment]
@jtsen 
I understood your point.  I updated the assumptions from `promotions/{id}/activate'` to  `PUT /promotions/{id} { status : "activate"}`

If you have more comments let's talk in the next meeting!

**Comment by shihokuni** [comment]
We got a comment from the professor.


> I think activate/deactivate are excellent choices for an action. Even if all it did was flip a status field, it is still a convenient way of expressing the change in state. You do not have to interact with other microservices for the homework, but you are correct that in "real life", activating a promotion may send out emails and other activities. That is exactly why we would use them.
